#!/bin/bash
# vim: set ts=4 et sw=4

indir="$1"
outdir="$2"
keyid="$3"

DISTS_VM_DEBIAN="jessie stretch buster bullseye"
DISTS_VM_FEDORA="fc30 fc31 fc32"
if echo "$indir" | grep -q -F '4.1'; then
DIST_DOM0="fc32"
else
DIST_DOM0="fc25"
fi

set -e
set -x

# sanity checks
[ -n "$indir" ]
[ -d "$indir" ]
[ -n "$outdir" ]

if [ -z "$keyid" ]; then
    keyid_from_rpm="$(rpm --eval %_gpg_name)"
    if [ -n "$keyid_from_rpm" ]; then
        keyid="$keyid_from_rpm"
    else
        keyid=TEST
    fi
fi

handle_rpm_repo() {
    local dir="$1"
    find "$dir" -name '*.rpm' -exec rpmsign --key-id="$keyid" --addsign {} +
    createrepo_c --update "$dir"
}

calc_sha1() {
    local f=$1
    echo -n " "
    echo -n "$(sha1sum "$f"|cut -d' ' -f 1)" ""
    echo -n "$(stat -c %s "$f")" ""
    echo "$1"
}

calc_sha256() {
    local f=$1
    echo -n " "
    echo -n "$(sha256sum "$f"|cut -d' ' -f 1)" ""
    echo -n "$(stat -c %s "$f")" ""
    echo "$1"
}

handle_deb_repo() {
    local dir="$1"
	local DIST="$2"
	local DIST_TAG=$3

	pushd "$dir"
	mkdir -p "dists/$DIST/main/binary-amd64"
	dpkg-scanpackages --multiversion --arch ".*$DIST_TAG.*" . > "dists/$DIST/main/binary-amd64/Packages"
	gzip -9c "dists/$DIST/main/binary-amd64/Packages" > "dists/$DIST/main/binary-amd64/Packages.gz"
	cat > "dists/$DIST/Release" <<EOF
Label: Test repo
Suite: $DIST
Codename: $DIST
Date: $(date -u +"%a, %d %b %Y %H:%M:%S %Z")
Architectures: amd64
Components: main
SHA1:
EOF
	(cd "dists/$DIST"; calc_sha1 main/binary-amd64/Packages) >> "dists/$DIST/Release"
	echo "SHA256:" >> "dists/$DIST/Release"
	(cd "dists/$DIST"; calc_sha256 main/binary-amd64/Packages) >> "dists/$DIST/Release"

	rm -f "dists/$DIST/Release.gpg"
	rm -f "dists/$DIST/InRelease"
	gpg --digest-algo=SHA256 -abs -u "$keyid" \
		< "dists/$DIST/Release" > "dists/$DIST/Release.gpg"
	gpg --digest-algo=SHA256 -a -s --clearsign -u "$keyid" \
		< "dists/$DIST/Release" > "dists/$DIST/InRelease"
	popd

	if [ "$(id -u)" -eq 0 ]; then
		chown -R --reference="$dir" "$dir"
	fi
}

mkdir -p "$outdir"

if [ "$(basename "$indir")" == vm ]; then
    for dist in $DISTS_VM_FEDORA; do
        mkdir -p "$outdir/vm/$dist/rpm"
        if [ -d "$indir/$dist" ]; then
            find "$indir/$dist" -name '*.rpm' -exec cp -t "$outdir/vm/$dist/rpm" {} +
        fi
        handle_rpm_repo "$outdir/vm/$dist"
    done
fi

for dist in $DISTS_VM_DEBIAN; do
    mkdir -p "$outdir/vm/pool"
    if [ "$dist" = "jessie" ]; then
        dist_tag=deb8
    elif [ "$dist" = "stretch" ]; then
        dist_tag=deb9
    elif [ "$dist" = "buster" ]; then
        dist_tag=deb10
    elif [ "$dist" = "bullseye" ]; then
        dist_tag=deb11
    fi
    if [ -d "$indir" ]; then
        find "$indir" -name "*${dist_tag}*.deb" -exec cp -t "$outdir/vm/pool" {} +
    fi
    handle_deb_repo "$outdir/vm" "$dist" "$dist_tag"
done

if [ "$(basename "$indir")" == dom0 ]; then
    for dist in $DIST_DOM0; do
        mkdir -p "$outdir/dom0/rpm"
        if [ -d "$indir/$dist" ]; then
            find "$indir/$dist" -name '*.rpm' -exec cp -t "$outdir/dom0/rpm" {} +
        fi
        handle_rpm_repo "$outdir/dom0"
    done
fi