#!/bin/bash

set -e -x

localdir="$(readlink -f "$(dirname "$0")")"
builder=$1
rel=$2
build=$3
flavor=${4:-pull-requests}
host=${5:-openqa.qubes-os.org}
shift 5

exit_clean() {
    local exit_code=$?
    rm -rf "$builddir"
    exit "${exit_code}"
}

[ -d "$builder" ] || exit 1
[ -d "$builder/qubes-src/linux-yum/r$rel" ] || exit 1
[ -n "$build" ] || exit 1

trap 'exit_clean' 0 1 2 3 6 15

builddir="$localdir/$build"
mkdir -p "$builddir/dom0/rpm"
find "$builder/qubes-src/linux-yum/r$rel"/templates-*-testing -name '*.rpm' -exec cp -t "$builddir/dom0/rpm" {} +

"$localdir/create-test-repo" "$builder/qubes-src/linux-yum/r$rel/unstable/dom0" "$builddir"
"$localdir/create-test-repo" "$builder/qubes-src/linux-yum/r$rel/unstable/vm" "$builddir"
"$localdir/create-test-repo" "$builder/qubes-src/linux-deb/r$rel/vm" "$builddir"

rsync -av --progress "$builddir/" "$host:/var/lib/openqa/factory/repo/$build"

# mitigate clock skew on whonix...
sleep 60

openqa-client --host "https://$host" isos post \
    DISTRI=qubesos \
    VERSION="$rel" \
    FLAVOR="$flavor" \
    ARCH=x86_64 \
    BUILD="$build-$rel" \
    REPO_1="$build" \
    UPDATE=1 \
    "$@"